name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Test build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - run: npm i
      - run: npm run build

  lint:
    name: Check linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - run: npm i
      - run: npm run lint
